id: I2FB17B2B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:02:52+00:00'
last_modified: '2022-06-07T16:50:16.685264+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG8897
  title: གསུང་འབུམ། ཤཱཀྱ་མཆོག་ལྡན། ༼རྫོང་སར་ཁམས་བྱེའི་གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    FF18:
      image_group_id: I1KG8943
      title: ''
      total_pages: 824
      order: 1
      base_file: FF18.txt
    F8F6:
      image_group_id: I1KG8944
      title: ''
      total_pages: 874
      order: 2
      base_file: F8F6.txt
    562D:
      image_group_id: I1KG8945
      title: ''
      total_pages: 726
      order: 3
      base_file: 562D.txt
    C75E:
      image_group_id: I1KG8946
      title: ''
      total_pages: 808
      order: 4
      base_file: C75E.txt
    D411:
      image_group_id: I1KG8947
      title: ''
      total_pages: 624
      order: 5
      base_file: D411.txt
    51A6:
      image_group_id: I1KG8948
      title: ''
      total_pages: 892
      order: 6
      base_file: 51A6.txt
    3FC2:
      image_group_id: I1KG8949
      title: ''
      total_pages: 810
      order: 7
      base_file: 3FC2.txt
    B496:
      image_group_id: I1KG8950
      title: ''
      total_pages: 732
      order: 8
      base_file: B496.txt
    '8536':
      image_group_id: I1KG8951
      title: ''
      total_pages: 940
      order: 9
      base_file: 8536.txt
    34E2:
      image_group_id: I1KG8952
      title: ''
      total_pages: 766
      order: 10
      base_file: 34E2.txt
    DB4D:
      image_group_id: I1KG8953
      title: ''
      total_pages: 754
      order: 11
      base_file: DB4D.txt
    F2EE:
      image_group_id: I1KG8954
      title: ''
      total_pages: 810
      order: 12
      base_file: F2EE.txt
    '8657':
      image_group_id: I1KG8955
      title: ''
      total_pages: 884
      order: 13
      base_file: 8657.txt
    4DFE:
      image_group_id: I1KG8956
      title: ''
      total_pages: 902
      order: 14
      base_file: 4DFE.txt
    A996:
      image_group_id: I1KG8957
      title: ''
      total_pages: 958
      order: 15
      base_file: A996.txt
    4D8C:
      image_group_id: I1KG8958
      title: ''
      total_pages: 802
      order: 16
      base_file: 4D8C.txt
    9B90:
      image_group_id: I1KG8959
      title: ''
      total_pages: 818
      order: 17
      base_file: 9B90.txt
    66CD:
      image_group_id: I1KG8960
      title: ''
      total_pages: 902
      order: 18
      base_file: 66CD.txt
    044B:
      image_group_id: I1KG8961
      title: ''
      total_pages: 1072
      order: 19
      base_file: 044B.txt
    BD8B:
      image_group_id: I1KG8962
      title: ''
      total_pages: 792
      order: 20
      base_file: BD8B.txt
    E1F2:
      image_group_id: I1KG8963
      title: ''
      total_pages: 484
      order: 21
      base_file: E1F2.txt
    '5915':
      image_group_id: I1KG8964
      title: ''
      total_pages: 768
      order: 22
      base_file: 5915.txt
    '3574':
      image_group_id: I1KG8965
      title: ''
      total_pages: 712
      order: 23
      base_file: 3574.txt
    '4193':
      image_group_id: I1KG8966
      title: ''
      total_pages: 470
      order: 24
      base_file: 4193.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
